apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor
  namespace: devops-tech-test
spec:
  selector:
    matchLabels:
      app: devops-tech-test-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - devops-tech-test
